gene:
    represented_as: node
    preferred_id: hgnc.symbol

transcription factor:
    is_a: gene
    represented_as: node
    preferred_id: hgnc.symbol

transcriptional regulation:
    is_a: pairwise gene to gene interaction
    represented_as: edge
    source: transcription factor
    target: gene
